-- CreateTable
CREATE TABLE "covid_testes" (
    "id" SERIAL NOT NULL,
    "notificacao_data" TIMESTAMPTZ,
    "cadastro_data" TIMESTAMPTZ,
    "diagnostico_data" TIMESTAMPTZ,
    "coleta_rt_pcr_data" TIMESTAMPTZ,
    "coleta_teste_rapido_data" TIMESTAMPTZ,
    "coleta_sorologia_data" TIMESTAMPTZ,
    "coleta_sorologia_igg_data" TIMESTAMPTZ,
    "encerramento_data" TIMESTAMPTZ,
    "obito_data" TIMESTAMPTZ,
    "classificacao" VARCHAR(100),
    "evolucao" VARCHAR(100),
    "confirmacao_criterio" VARCHAR(100),
    "status_notificacao" VARCHAR(100),
    "municipio" VARCHAR(100),
    "bairro" VARCHAR(100),
    "faixa_etaria" VARCHAR(100),
    "idade_data_notificacao" VARCHAR(100),
    "sexo" VARCHAR(100),
    "raca_cor" VARCHAR(100),
    "escolaridade" VARCHAR(100),
    "gestante" BOOLEAN,
    "febre" BOOLEAN,
    "dificuldade_respiratoria" BOOLEAN,
    "tosse" BOOLEAN,
    "coriza" BOOLEAN,
    "dor_garganta" BOOLEAN,
    "diarreia" BOOLEAN,
    "cefaleia" BOOLEAN,
    "pulmao_comorbidade" BOOLEAN,
    "cardio_comorbidade" BOOLEAN,
    "rins_comorbidade" BOOLEAN,
    "diabetes_comorbidade" BOOLEAN,
    "tabagismo_comorbidade" BOOLEAN,
    "obesidade_comorbidade" BOOLEAN,
    "ficou_internado" BOOLEAN,
    "viagem_internacional" VARCHAR(100),
    "viagem_brasil" VARCHAR(100),
    "profissional_saude" VARCHAR(100),
    "possui_deficiencia" VARCHAR(100),
    "morador_de_rua" VARCHAR(100),
    "rt_pcr_resultado" VARCHAR(100),
    "teste_rapido_resultado" VARCHAR(100),
    "sorologia_resultado" VARCHAR(100),
    "sorologia_igg_resultado" VARCHAR(100),
    "tipo_teste_rapido" VARCHAR(100),

    CONSTRAINT "covid_testes_pkey" PRIMARY KEY ("id")
);
